- dashboard: multiple_value_dev
  title: Multiple Value Dev
  layout: newspaper
  elements:
  - title: New Tile
    name: New Tile
    model: system__activity
    explore: history
    type: single_value
    fields: [history.queries_under_10s, history.query_run_count, history.approximate_usage_in_minutes,
      history.total_runtime]
    limit: 500
    column_limit: 50
    custom_color_enabled: true
    show_single_value_title: true
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    custom_color: "#ed6168"
    single_value_title: Queries Under 10s
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: false
    font_size_main: ''
    style_history.database_result_query_count: "#5245ed"
    show_title_history.database_result_query_count: true
    title_placement_history.database_result_query_count: above
    value_format_history.database_result_query_count: ''
    show_comparison_history.cache_result_query_count: true
    comparison_style_history.cache_result_query_count: calculate_progress_perc
    comparison_show_label_history.cache_result_query_count: true
    comparison_label_history.cache_result_query_count: ''
    comparison_label_placement_history.cache_result_query_count: below
    style_history.queries_under_10s: "#ed6168"
    show_title_history.queries_under_10s: true
    title_placement_history.queries_under_10s: above
    value_format_history.queries_under_10s: ''
    show_comparison_history.queries_under_10s: false
    show_comparison_history.query_run_count: true
    comparison_style_history.query_run_count: calculate_progress_perc
    comparison_show_label_history.query_run_count: true
    comparison_label_placement_history.query_run_count: below
    style_history.approximate_usage_in_minutes: "#1ea8df"
    show_title_history.approximate_usage_in_minutes: true
    title_placement_history.approximate_usage_in_minutes: above
    value_format_history.approximate_usage_in_minutes: ''
    show_comparison_history.approximate_usage_in_minutes: false
    show_comparison_history.total_runtime: true
    comparison_style_history.total_runtime: calculate_progress_perc
    comparison_show_label_history.total_runtime: true
    comparison_label_placement_history.total_runtime: below
    style_history.total_runtime: "#3A4245"
    show_title_history.total_runtime: true
    title_placement_history.total_runtime: above
    value_format_history.total_runtime: ''
    style_history.query_run_count: "#3A4245"
    show_title_history.query_run_count: true
    title_placement_history.query_run_count: above
    value_format_history.query_run_count: ''
    comparison_style_history.queries_under_10s: calculate_progress_perc
    comparison_show_label_history.queries_under_10s: true
    comparison_label_placement_history.queries_under_10s: below
    style_history.cache_result_query_count: "#3A4245"
    show_title_history.cache_result_query_count: true
    title_placement_history.cache_result_query_count: above
    value_format_history.cache_result_query_count: ''
    style_history.average_runtime: "#9d63ad"
    show_title_history.average_runtime: true
    title_placement_history.average_runtime: above
    value_format_history.average_runtime: ''
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    show_x_axis_label: true
    show_x_axis_ticks: true
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    show_value_labels: false
    label_density: 25
    x_axis_scale: auto
    y_axis_combined: true
    ordering: none
    show_null_labels: false
    show_totals_labels: false
    show_silhouette: false
    totals_color: "#808080"
    defaults_version: 1
    series_types: {}
    listen: {}
    row: 6
    col: 9
    width: 6
    height: 5
  - title: New Tile
    name: New Tile (2)
    model: system__activity
    explore: history
    type: mp-viz::multiple-value-dev
    fields: [history.database_result_query_count, history.cache_result_query_count,
      history.queries_under_10s, history.query_run_count, history.approximate_usage_in_minutes,
      history.total_runtime]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: false
    font_size_main: ''
    style_history.database_result_query_count: "#5245ed"
    show_title_history.database_result_query_count: true
    title_placement_history.database_result_query_count: below
    value_format_history.database_result_query_count: ''
    show_comparison_history.cache_result_query_count: true
    comparison_style_history.cache_result_query_count: calculate_progress_perc
    comparison_show_label_history.cache_result_query_count: true
    comparison_label_history.cache_result_query_count: ''
    comparison_label_placement_history.cache_result_query_count: below
    style_history.queries_under_10s: "#FBB555"
    show_title_history.queries_under_10s: true
    title_placement_history.queries_under_10s: below
    value_format_history.queries_under_10s: ''
    show_comparison_history.queries_under_10s: false
    show_comparison_history.query_run_count: true
    comparison_style_history.query_run_count: calculate_progress_perc
    comparison_show_label_history.query_run_count: true
    comparison_label_placement_history.query_run_count: below
    style_history.approximate_usage_in_minutes: "#1ea8df"
    show_title_history.approximate_usage_in_minutes: true
    title_placement_history.approximate_usage_in_minutes: below
    value_format_history.approximate_usage_in_minutes: ''
    show_comparison_history.approximate_usage_in_minutes: false
    show_comparison_history.total_runtime: true
    comparison_style_history.total_runtime: calculate_progress_perc
    comparison_show_label_history.total_runtime: true
    comparison_label_placement_history.total_runtime: below
    style_history.total_runtime: "#3A4245"
    show_title_history.total_runtime: true
    title_placement_history.total_runtime: above
    value_format_history.total_runtime: ''
    style_history.query_run_count: "#3A4245"
    show_title_history.query_run_count: true
    title_placement_history.query_run_count: above
    value_format_history.query_run_count: ''
    comparison_style_history.queries_under_10s: calculate_progress_perc
    comparison_show_label_history.queries_under_10s: true
    comparison_label_placement_history.queries_under_10s: below
    style_history.cache_result_query_count: "#3A4245"
    show_title_history.cache_result_query_count: true
    title_placement_history.cache_result_query_count: above
    value_format_history.cache_result_query_count: ''
    style_history.average_runtime: "#9d63ad"
    show_title_history.average_runtime: true
    title_placement_history.average_runtime: above
    value_format_history.average_runtime: ''
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    show_x_axis_label: true
    show_x_axis_ticks: true
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    show_value_labels: false
    label_density: 25
    x_axis_scale: auto
    y_axis_combined: true
    ordering: none
    show_null_labels: false
    show_totals_labels: false
    show_silhouette: false
    totals_color: "#808080"
    defaults_version: 0
    series_types: {}
    title_hidden: true
    listen: {}
    row: 0
    col: 0
    width: 24
    height: 6
